name: ge-version 
description: Get version from Cargo.toml

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl -SLO https://github.com/o0th/get-version/releases/download/0.2.1/get-version
        chmod +x get-version
        echo "$PWD" >> $GITHUB_PATH
