name: ge-version 
description: Get version from Cargo.toml

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -SLO https://github.com/o0th/get-version/releases/download/0.2.0/get-version
        chmod +x get-version
        mv get-version $GITHUB_WORKSPACE/bin/get-version
        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
