---
name: release 

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - action.yaml

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache
      - run: cargo build --release
      - run: echo "VERSION=$(./target/release/get-version)" >> $GITHUB_ENV
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/get-version-v${process.env.VERSION}`,
              sha: context.sha
            })
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "get-version-v${{ env.VERSION }}"
          bodyFile: ".github/changelogs/${{ env.VERSION }}.md"
          artifacts: "./target/release/get-version"
