---
name: testing

on:
  push:
    branches:
      - testing 

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: echo "Version: $(get-version)"
