---
name: testing

on:
  push:
    branches:
      - testing-action

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: ./get-version
